development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  
  # channel_prefix: shownola-what-sup_production
  
  # channel_prefix: WhatSup_production
  
  # url: redis://localhost:6379/1
